version: 2
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-1604:201903-01
      working_directory: /usr/local/bin/
    steps:
      - checkout
      - run: set -e
      - run: sudo wget https://releases.hashicorp.com/vault/1.5.4+ent/vault_1.5.4+ent_linux_amd64.zip -O /tmp/vault.zip
      - run: sudo unzip /tmp/vault.zip
      - run: sudo cp vault /usr/local/bin/vault
      - run: sudo chmod +x /usr/local/bin/vault
      - run: export VAULT_ADDR='http://127.0.0.1:8200'
      - run: sudo sh -c 'nohup /usr/local/bin/vault server -dev > /usr/local/bin/nohup.out &'
      - run: sleep 2
      - run: export ROOT_TOKEN=$(grep 'Root Token:' /usr/local/bin/nohup.out | awk '{print $NF}')
      - run: /usr/local/bin/vault login $ROOT_TOKEN
  policy:
    machine:
      image: ubuntu-1604:201903-01
      working_directory: /usr/local/bin/
    steps:
      - checkout
      - run:
          name: Vault Policy Testing
          command: |
            set -e
            cd /usr/local/bin
            export VAULT_ADDR='http://127.0.0.1:8200'
            export ROOT_TOKEN=$(grep 'Root Token:' nohup.out | awk '{print $NF}')
            /usr/local/bin/vault login $ROOT_TOKEN
            sleep 2
            /usr/local/bin/vault policy write user-policy user-policy.hcl
            sudo touch /usr/local/bin/user.out
            sudo sh -c '/usr/local/bin/vault token create -policy=user-policy > /usr/local/bin/user.out'
            export USER_TOKEN=$(grep -m 1 'token' /usr/local/bin/user.out | awk '{print $NF}')
            curl --header "X-Vault-Token: $ROOT_TOKEN" --request PUT --data @payload.json $VAULT_ADDR/v1/sys/policies/egp/deny-kv-v1-mount
            /usr/local/bin/vault login $USER_TOKEN
            /usr/local/bin/vault secrets enable -path=testing-user -version=1 kv
            curl --header "X-Vault-Token: $ROOT_TOKEN" --request PUT --data @payload-bad.json $VAULT_ADDR/v1/sys/policies/egp/deny-kv-v1-mount
            /usr/local/bin/vault secrets enable -path=testing-user2 -version=1 kv
            /usr/local/bin/vault secrets enable -path=testing-user3 -version=2 kv
            exit 0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - policy:
          requires:
            - build
          filters:
            branches:
              only: master