version: 2
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-1604:201903-01
      working_directory: /usr/local/bin/
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      ROOT_TOKEN: root
    steps:
      - checkout
      - run: set -e
      - run: sudo wget https://releases.hashicorp.com/vault/1.5.4+ent/vault_1.5.4+ent_linux_amd64.zip -O /tmp/vault.zip
      - run: sudo unzip /tmp/vault.zip
      - run: sudo cp vault /usr/local/bin/vault
      - run: sudo chmod +x /usr/local/bin/vault
      - run:
          command: |
            sudo sh -c 'nohup /usr/local/bin/vault server -dev -dev-root-token-id="root" > /usr/local/bin/nohup.out &'
            sleep 2
            cat /usr/local/bin/nohup.out
            sudo -E /usr/local/bin/vault login $ROOT_TOKEN
      - run:
          command: |
            sleep 2
            sudo -E /usr/local/bin/vault policy write user-policy user-policy.hcl
            sudo -E sh -c '/usr/local/bin/vault token create -policy=user-policy > /usr/local/bin/user.out'
            sudo -E sh -c 'echo "export USER_TOKEN=$(grep -m 1 "token" /usr/local/bin/user.out | awk "{print $NF}")"' >> $BASH_ENV
            source $BASH_ENV
            curl --header "X-Vault-Token: $ROOT_TOKEN" --request PUT --data @payload.json $VAULT_ADDR/v1/sys/policies/egp/deny-kv-v1-mount
            sudo -E /usr/local/bin/vault login $USER_TOKEN
            sudo -E /usr/local/bin/vault secrets enable -path=testing-user -version=1 kv
            curl --header "X-Vault-Token: $ROOT_TOKEN" --request PUT --data @payload-bad.json $VAULT_ADDR/v1/sys/policies/egp/deny-kv-v1-mount
            sudo -E /usr/local/bin/vault secrets enable -path=testing-user2 -version=1 kv
            sudo -E /usr/local/bin/vault secrets enable -path=testing-user3 -version=2 kv

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
